title: Yim Lab at KAIST
first_name: Sung Sun
middle_name: null
last_name: Yim
email: yimlabkaist@gmail.com
description: null
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a
  href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted by <a
  href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: null
lang: en
icon: null
url: 'https://yimlabkaist.github.io'
baseurl: null
last_updated: false
impressum_path: null
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed
rss_icon: false
navbar_fixed: true
footer_fixed: true
max_width: 800px
serve_og_meta: true
serve_schema_org: true
og_image: null
github_username: yimlabkaist
gitlab_username: null
x_username: sungsyim
mastodon_username: null
linkedin_username: null
telegram_username: null
scholar_userid: TomSdzEAAAAJ
semanticscholar_id: null
whatsapp_number: null
orcid_id: null
medium_username: null
quora_username: null
publons_id: null
lattes_id: null
osf_id: null
research_gate_profile: null
scopus_id: null
blogger_url: null
work_url: null
keybase_username: null
wikidata_id: null
wikipedia_id: null
dblp_url: null
stackoverflow_id: null
kaggle_id: null
lastfm_id: null
spotify_id: null
pinterest_id: null
unsplash_id: null
instagram_id: null
facebook_id: null
youtube_id: null
discord_id: null
zotero_username: null
wechat_qr: null
contact_note: ''
google_analytics: G-VJ2KED3RJ2
cronitor_analytics: null
google_site_verification: null
bing_site_verification: null
blog_name: al-folio
blog_description: a simple whitespace theme for academics
permalink: '/blog/:year/:title/'
pagination:
  enabled: true
related_blog_posts:
  enabled: true
  max_related: 5
giscus:
  repo: null
  repo_id: null
  category: Comments
  category_id: null
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en
disqus_shortname: al-folio
external_sources:
  - name: medium.com
    rss_url: 'https://medium.com/@al-folio/feed'
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: '/news/:path/'
  projects:
    output: true
    permalink: '/projects/:path/'
announcements:
  enabled: true
  scrollable: true
  limit: 5
latest_posts:
  enabled: false
  scrollable: true
  limit: 3
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
  - _pages
exclude:
  - bin
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - docker-compose.yml
  - Dockerfile
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - vendor
keep_files:
  - CNAME
  - .nojekyll
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
defaults:
  - scope:
      path: assets
    values:
      sitemap: false
sass:
  style: compressed
jekyll-minifier:
  exclude:
    - robots.txt
  uglifier_args:
    harmony: true
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'
display_tags:
  - formatting
  - images
  - links
  - math
  - code
display_categories:
  - blockquotes
scholar:
  last_name:
    - Yim
  first_name:
    - Sung Sun
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
    - latex
    - smallcaps
    - superscript
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: '@*'
  group_by: year
  group_order: descending
enable_publication_badges:
  altmetric: true
  dimensions: true
filtered_bibtex_keywords:
  - abbr
  - abstract
  - altmetric
  - arxiv
  - bibtex_show
  - blog
  - code
  - html
  - pdf
  - poster
  - preview
  - selected
  - slides
  - supp
  - video
  - website
max_author_limit: null
more_authors_animation_delay: null
enable_publication_thumbnails: false
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude: null
imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - .jpg
    - .jpeg
    - .png
    - .tiff
    - .gif
  output_formats:
    webp: '-quality 85'
enable_google_analytics: true
enable_cronitor_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
bootstrap-table:
  version: 1.22.1
chartjs:
  version: 4.4.1
d3:
  version: 7.8.5
  integrity: sha256-1rA678n2xEx7x4cTZ5x4wpUCj6kUMZEZ5cxLSVSFWxw=
diff2html:
  version: 3.4.47
  integrity:
    css: sha256-IMBK4VNZp0ivwefSn51bswdsrhk0HoMTLc2GqFHFBXg=
    js: sha256-eU2TVHX633T1o/bTQp6iIJByYJEtZThhF9bKz/DcbbY=
echarts:
  version: 5.4.3
  integrity:
    library: sha256-EVZCmhajjLhgTcxlGMGUBtQiYULZCPjt0uNTFEPFTRk=
    dark_theme: sha256-UmFIP/4VvOqBDIl2QWl1HBuAJ1XWs/iFZxT5yJRZOKo=
highlightjs:
  version: 11.9.0
  integrity:
    css:
      light: sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2fZ/6ksAqDCM8GY=
      dark: sha256-nyCNAiECsdDHrr/s2OQsp5l9XeY2ZJ0rMepjCT2AkBk=
imagesloaded:
  version: 5.0.0
  integrity: sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc=
img-comparison-slider:
  version: 8.0.6
jquery:
  version: 3.6.0
  integrity: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
leaflet:
  version: 1.9.4
  integrity:
    css: sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=
    js: sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=
mathjax:
  version: 3.2.0
masonry:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.20.0
  integrity:
    css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
    js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
medium_zoom:
  version: 1.1.0
  integrity: sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc=
mermaid:
  version: 10.7.0
  integrity: sha256-TtLOdUA8mstPoO6sGvHIGx2ceXrrX4KgIItO06XOn8A=
swiper:
  version: 11.0.5
  integrity:
    css: sha256-yUoNxsvX+Vo8Trj3lZ/Y5ZBf8HlBFsB6Xwm7rH75/9E=
    js: sha256-BPrwikijIybg9OQC5SYFFqhBjERYOn97tCureFgYH1E=
vega:
  version: 5.27.0
  integrity: sha256-Yot/cfgMMMpFwkp/5azR20Tfkt24PFqQ6IQS+80HIZs=
vega-embed:
  version: 6.24.0
  integrity: sha256-FPCJ9JYCC9AZSpvC/t/wHBX7ybueZhIqOMjpWqfl3DU=
vega-lite:
  version: 5.16.3
  integrity: sha256-TvBvIS5jUN4BSy009usRjNzjI1qRrHPYv7xVLJyjUyw=
jekyll_get_json:
  - data: resume
    json: assets/json/resume.json
jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
